/*
 * ScanUnkownReportDialog.java
 *
 * Created on 1. Januar 2002, 12:42
 */

package org.jsynthlib.core.viewcontroller;

import java.awt.BorderLayout;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.border.EmptyBorder;

/**
 * @author Gerrit Gehnen
 */
public class ScanUnkownReportDialog extends JDialog {

    private static final long serialVersionUID = 1L;

    private final Clipboard clipbrd;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel rowOneLabel;
    private JPanel buttonPanel;
    private JButton closeButton;
    private JPanel headerPanel;
    private JLabel rowTwoLabel;
    private JButton copyButton;
    private JScrollPane jScrollPane1;
    private JTextArea reportArea;

    // End of variables declaration//GEN-END:variables

    /** Creates new form ScanUnkownReportDialog */
    public ScanUnkownReportDialog(Dialog parent, boolean modal) {
        super(parent, modal);
        clipbrd = getToolkit().getSystemClipboard();
        initComponents();
        getRootPane().setDefaultButton(closeButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        jScrollPane1 = new JScrollPane();
        reportArea = new JTextArea();
        headerPanel = new JPanel();
        rowOneLabel = new JLabel();
        rowTwoLabel = new JLabel();
        buttonPanel = new JPanel();
        copyButton = new JButton();
        closeButton = new JButton();

        getContentPane().setLayout(new BorderLayout(0, 5));

        setTitle("Unkown Devices found!");
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jScrollPane1.setPreferredSize(new Dimension(300, 200));
        reportArea.setPreferredSize(new Dimension(200, 172));
        jScrollPane1.setViewportView(reportArea);

        getContentPane().add(jScrollPane1, BorderLayout.CENTER);

        headerPanel.setLayout(new GridLayout(2, 0, 5, 0));

        headerPanel.setBorder(new EmptyBorder(new Insets(10, 10, 10,
                10)));
        rowOneLabel.setText("The following unkown devices are found!");
        headerPanel.add(rowOneLabel);

        rowTwoLabel
                .setText("Please send an email to <jsynthlib@overwhelmed.org> and include the following report.");
        headerPanel.add(rowTwoLabel);

        getContentPane().add(headerPanel, BorderLayout.NORTH);

        copyButton.setText("Copy report to clipboard");
        copyButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(copyButton);

        closeButton.setText("Close");
        closeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(closeButton);

        getContentPane().add(buttonPanel, BorderLayout.SOUTH);

        pack();
    }

    private void copyButtonActionPerformed(ActionEvent evt) {
        StringSelection text = new StringSelection(reportArea.getText());
        clipbrd.setContents(text, text);
    }

    private void closeButtonActionPerformed(ActionEvent evt) {
        setVisible(false);
        dispose();
    }

    /** Closes the dialog */
    private void closeDialog(WindowEvent evt) {
        setVisible(false);
        dispose();
    }

    public void addToReport(String text) {
        reportArea.append(text);
        reportArea.updateUI();
    }
}
